format = """
[](#1C4961)\
$username\
$hostname\
[](bg:#2F79A1 fg:#1C4961)\
$directory\
[](bg:#3A95C7 fg:#2F79A1)\
$git_branch\
[](bg:#40A9E0 fg:#3A95C7)\
$git_status\
[ ](bg:none fg:#40A9E0)\
$nodejs
"""

add_newline = false

[username]
show_always = true
style_user = "bg:#1C4961"
style_root = "bg:#1C4961"
format = '[$user]($style)'
disabled = false

[directory]
style = "bg:#2F79A1"
format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Dokumente" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Musik" = " "
"Pictures" = " "
"Bilder" = " "

[git_branch]
# symbol = ""
style = "bg:#3A95C7"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "bg:#40A9E0"
format = '[ $all_status$ahead_behind ]($style)'

[hostname]
disabled = false
style = "bg:#1C4961"
format = '[$ssh_symbol]($style bold blue)[@]($style)[$hostname ]($style bold)'
ssh_only = false